# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='displayName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='photoURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
